### ISSUE TITLE
Error when initialize database

### ISSUE THREAD

**Issue by moontai0724** [moontai0724/knowledge-king-back-end#1]
When initialize database, which is usually running at first-time startup, will cause this error and failed to create database tables:
```
QueryFailedError: Duplicate key name 'IDX_e12875dfb3b1d92d7d7c5377e2'
    at new QueryFailedError (/home/node/app/node_modules/typeorm/error/QueryFailedError.js:12:28)
    at Query.onResult (/home/node/app/node_modules/typeorm/driver/mysql/MysqlQueryRunner.js:217:45)
    at Query.execute (/home/node/app/node_modules/mysql2/lib/commands/command.js:30:14)
    at PoolConnection.handlePacket (/home/node/app/node_modules/mysql2/lib/connection.js:425:32)
    at PacketParser.onPacket (/home/node/app/node_modules/mysql2/lib/connection.js:75:12)
    at PacketParser.executeStart (/home/node/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/home/node/app/node_modules/mysql2/lib/connection.js:82:25)
    at Socket.emit (node:events:369:20)
    at addChunk (node:internal/streams/readable:313:12)
    at readableAddChunk (node:internal/streams/readable:288:9)
```
![console log](https://user-images.githubusercontent.com/25532663/116541207-bfaf1400-a91d-11eb-92ca-b54ac651fa83.png)

But if tables already exists, will not trigger this problem.

**Comment by moontai0724** [comment]
Problem confirmed and  resolved.

If set `autoLoadEntities` to `true`, it will load schemas twice or more, then cause this issue.

To solve this issue, set `autoLoadEntites` to `false`, and set `entities` correctly in TypeORM Initialize parameter. 

Resolved in 5850ac7c
